### ISSUE TITLE
UI Nitpicks

### ISSUE THREAD

**Issue by jannuary** [nlogozzo/NickvisionTagger#12]
# List
- The list view is odd. I don't think you can use a boxed list here, so it would make sense to simply remove the broken background.
- Similarly, the scrollbar isn't on the edge of the window.
- The list isn't clamped, so it's a bit silly on large window sizes. Use [AdwClamp](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.Clamp.html) or [AdwClampScrollable](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.ClampScrollable.html).
![image](https://user-images.githubusercontent.com/27908024/170853610-ac42113d-2808-424a-842e-827a8343f170.png)

# Tag Editor
- There's no separator between the list and the editor pane.
- Just like the List, this has margins on the scrolled view, so the scrollbar is floating and the list scrolls into nothingness.
- I can't seem to navigate with the keyboard to the editor?
- Some of these fields are not editable without any indication.
![image](https://user-images.githubusercontent.com/27908024/170853756-1086240d-cb24-4178-99be-ca0984fa6b1f.png)

# Headerbar 
- Some icons are missing.
- "Save" and "Remove" buttons should probably be on the righthand side.
- I'm not sure if "Filename to Tag" and "Tag to Filename" make sense as icon-only or buttons on the headerbar at all. 
![image](https://user-images.githubusercontent.com/27908024/170854003-ed5bed01-f8a7-4e06-8089-001064aa5ecd.png)

# Primary Menu
- The tooltip is "Help"?
- "Github Repo", "Report a Bug" and "Changelog" are redundant - the about dialog already links to the repo.

**Comment by nlogozzo** [comment]
I will definitely fix the scroll bars of the list view and tag editor for the next release.

As far as `There's no separator between the list and the editor pane.` I thought the color contrast from the ListView would be separation enough but I'd be happy to add in a separator.

For `Some of these fields are not editable without any indication.` I mean the only fields not editable would be Duration and File Size because I think it's obvious you can't manually change a song's duration and/or file size.

For `Some icons are missing.` my fault as I'm using `papirus-icon-theme` . I will change to adwaita theme and choose the appropriate icon names

For `I'm not sure if "Filename to Tag" and "Tag to Filename" make sense as icon-only or buttons on the headerbar at all.` In the next release I'm planning to hide all these buttons in the header bar and only show them when items in the ListView are selected

For `The tooltip is "Help"?` I'll remove the tooltip

For `"Github Repo", "Report a Bug" and "Changelog" are redundant - the about dialog already links to the repo.` Yeah you're right. I think i'm going to keep "Changelog" but "GitHub Repo" and "Report a Bug" I will remove in favor of the link in the about dialog.

**Comment by jannuary** [comment]
> For The tooltip is "Help"? I'll remove the tooltip

It should be "Open Menu", as per [HIG](https://developer.gnome.org/hig/patterns/feedback/tooltips.html) :)

**Comment by nlogozzo** [comment]
Ah even better :)

**Comment by nlogozzo** [comment]
Coming in next release. You can build from 2022.5.3 branch to test out.

Files Not Selected:
![image](https://user-images.githubusercontent.com/17648453/170869058-49c1c656-e202-4d14-a99b-e9264d9035ff.png)
Files Selected:
![image](https://user-images.githubusercontent.com/17648453/170869021-9f5627e0-4634-4963-860e-9d0bd9bc8146.png)

**Comment by nlogozzo** [comment]
Light Theme:
![image](https://user-images.githubusercontent.com/17648453/170869098-d4ba088f-fd1f-42fa-896a-3a28e2bc15e7.png)
![image](https://user-images.githubusercontent.com/17648453/170869108-b75ed158-f7c9-466b-8230-10406eecf101.png)

**Comment by nlogozzo** [comment]
And with Adwaita icons this time xD
![image](https://user-images.githubusercontent.com/17648453/170869241-0b46f593-2732-4f52-a6a6-1b383e0ccefc.png)

**Comment by nlogozzo** [comment]
New Design!
- Save Tag has been renamed to Apply and placed on the right
- The icon next to the Apply button is a submenu that contains actions such as Remove Tag, Filename to Tag, Tag to Filename, and Download Metadata
- All actions bounded by keyboard shortcuts

![image](https://user-images.githubusercontent.com/17648453/170877268-958bf028-c0eb-43c6-87fc-d8cf0b889884.png)

**Comment by nlogozzo** [comment]
[V2022.5.3](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.5.3)

**Comment by jannuary** [comment]
'Open' shouldn't be flat like that: it should either have an arrow or an icon.
![image](https://user-images.githubusercontent.com/27908024/170986442-1e01fa4b-b575-452b-a232-44154694f5b6.png)

e.g.
![image](https://user-images.githubusercontent.com/27908024/170986584-bc81cfad-a8c7-4738-95fc-a7860cfa5bb2.png)
![image](https://user-images.githubusercontent.com/27908024/170986621-1ae4f1dc-a179-4468-95ec-cc8e7c0e4793.png)

**Comment by nlogozzo** [comment]
Adding an icon for V2022.5.4

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/170999759-ceb7f787-c8e3-4129-ba05-cff7aa9f05a6.png)
