### ISSUE TITLE
Add to flathub

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionTagger#5]
Get the application uploaded to flathub to make distribution easier.

**Comment by jannuary** [comment]
Prerequisites:
- A .desktop file
- An appdata file
- Stop hardcoding GCR_Cmake dir
- Use GtkFileChooserNative instead of GtkFileChooser
- Remove 'Update' from the primary menu

I have a manifest on my [branch](https://github.com/jannuary/NickvisionTagger/tree/flatpak-test), though it isn't yet functional.

**Comment by nlogozzo** [comment]
Flatpak is giving me a lot of problems, however I have released the app on the AUR: [NickvisionTagger](https://aur.archlinux.org/packages/nickvision-tagger)

**Comment by jannuary** [comment]
What kind of problems?

**Comment by nlogozzo** [comment]
I was able to get the app installed, you can look at the previous commits for the json manifest. However, I cannot figure out the correct path for /usr/share where I store the UI files

**Comment by nlogozzo** [comment]
Use https://github.com/flathub/flathub/pull/3267 to track
