### ISSUE TITLE
UI: after "Apply" the change, the list scrolls back to the top

### ISSUE THREAD

**Issue by tomastan** [nlogozzo/NickvisionTagger#51]
**The problem**

When you have many files to change you go through the list one by one. After each save you are thrown back to the top of the list and must find the position to continue yet again.

**To reproduce**

1. Open longer list of songs. 
2. Select a song in the middle.
3. Modify the tag and click "Apply"

**Result** 
The list is on the top

**Expected result**
The list stays the same place

**Comment by nlogozzo** [comment]
Thanks for the report!
When you click the 'Apply' button, Tagger saves the changes and then reloads the music folder (in case the filename was changed and it needs to update the row). So that is why the list scrolls back to the top because all the rows are removed and then added again.
What I can do is track the last selected file before you click 'Apply' and then have Tagger re-select that file after 'Apply' is clicked so you are scrolled back to your previous position.

**Comment by tomastan** [comment]
Great. That sounds as a great usability improvement for a long list editing.

**Comment by nlogozzo** [comment]
Ok i was able to have Tagger remember and re-select the previously selected row. However, GtkListBox doesn't automatically scroll to the row...which defeats the whole purpose. I will try to find a way.

**Comment by nlogozzo** [comment]
Yeah you can change the filename that's the only problem since a change requires a reload so it updates the row in the list. I will change it to make it where the row will be updated directly if a filename is changed instead of requiring a reload.

**Comment by tomastan** [comment]
It's perfect now. Great job!
