### ISSUE TITLE
Feature request: search for empty tags

### ISSUE THREAD

**Issue by tomastan** [nlogozzo/NickvisionTagger#55]
In larger libraries it's hard to find which file has missing tags. You should go one by one and look for incomplete ones. It would be convenient to have a tool to filter out those. Possible ideas to consider:

* Present the list as a sortable table with tags as columns. So could be sorted by artist name with empty on top. Easier to manage, but may complicate the interface look.
* Make more sophisticated search. For example "artist:(empty)". UI stays the same, but it's not so obvious for beginners.

**Comment by nlogozzo** [comment]
Love the idea! I will try to design some mockups and try to get this implemented for the next release

**Comment by nlogozzo** [comment]
I think I'm going to go with the second option of a more sophisticated search.
I was thinking of creating a basic syntax with a `!` and the property you want to search for empty.
For example, `!artist` with filter the list with all the files that have empty artist tags.
How does that sound?

**Comment by tomastan** [comment]
It looks as a working solution. If something more sophisticated would be requested by users, you could always change it. Right?)

**Comment by nlogozzo** [comment]
Yes of course but for now it's the best solution I can think of instead of a convoluted `artist:(empty)`
We'll see how it goes when I implement it.

**Comment by nlogozzo** [comment]
Actually i think i'm going to go with a syntax like `!title="",artist="",...`
The `!` will signify advanced search and then you can search for empty properties or if properties contain a certain value

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/commit/7ebc0f68c5ee828d4f83ac74c59a7f17adf937da

Started `Advanced Search` feature. Here's the progress so far.
---
![NoSearch](https://user-images.githubusercontent.com/17648453/196582361-0b1d181b-0954-4cf8-8a38-2640b91ed6b9.png)
^ Advanced search not activated. Notice how search box says type `!` to activate it.

![StartAdvancedSearch](https://user-images.githubusercontent.com/17648453/196582455-13b064c4-0bf4-4cc9-b610-02b8b95844ca.png)
^ Advanced search is activated with `!`. Notice how to the right of the search box there is an information button. The textbox is red as the search string is not valid.

![AdvancedSearchInfo](https://user-images.githubusercontent.com/17648453/196582506-3849ae6a-6a9a-4d93-9c0a-d9e4ed266088.png)
^ Clicking the information button reveals a detailed description of how advanced search works.

![ValidAdvancedSearch](https://user-images.githubusercontent.com/17648453/196582668-18d2ea5f-ca31-4070-a64b-23f7a27623a1.png)
^ Here the provided search string is valid, thus the box is green (However, the actual list box filtering is not yet implemented). 

![DarkMode](https://user-images.githubusercontent.com/17648453/196582804-37b4967a-5492-4c67-93e7-9bcbfe300a87.png)
^ Same as above, but dark :) .

![RegularSearch](https://user-images.githubusercontent.com/17648453/196582832-d9d60d40-85f5-4691-b493-6945cd150cd4.png)
^ Here we see the regular search functionality that has been in previous versions of Tagger. Advanced search is not activated since the string does not start with `!` and thus just filenames will be searched.

**Comment by nlogozzo** [comment]
Please test: [V2022.10.4-beta2](https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.4-beta2)

**Comment by tomastan** [comment]
@nlogozzo Tried. Looks to work well for my needs, and all the songs are cleaned up now :).

Maybe a minor improvement to consider. When I found items without a tag, then add the tag, ideally I'd expect the item to disappear from the list, as it doesn't meet the criteria anymore. But it's minor. It's pretty useful even without this update.

**Comment by nlogozzo** [comment]
I will make it where when you apply changes to a tag and will trigger the search again and update the list.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTagger/releases/tag/2022.10.4

**Comment by nlogozzo** [comment]
> I will make it where when you apply changes to a tag it will trigger the search again and update the list.

^ this fix is included in the stable release.
